// Local appearance choices shared by the controls and preference validation.
export const boardSkins = Object.freeze([
  { id: 'ivory', label: '米白', detail: '温润米色' },
  { id: 'celadon', label: '青瓷', detail: '浅绿底色' },
  { id: 'mist', label: '雾蓝', detail: '清浅蓝灰' },
  { id: 'lotus', label: '浅藕', detail: '柔和藕粉' },
  { id: 'beech', label: '浅榉木', detail: '细直纤维 · 自然微孔' },
  { id: 'walnut', label: '浅胡桃木', detail: '舒展山纹 · 波状木理' },
  { id: 'maple', label: '浅枫木', detail: '柔细纤维 · 轻浅波纹' },
  { id: 'ash', label: '白蜡木', detail: '舒展山纹 · 细长微孔' },
  { id: 'golden-oak', label: '金橡木', detail: '层叠山纹 · 粗细交织' },
  { id: 'golden-nanmu', label: '金丝楠木', detail: '金丝流光 · 水波莹润' },
  { id: 'teak', label: '柚木', detail: '纵向直纹 · 深浅条带' },
  { id: 'cherry', label: '樱桃木', detail: '柔顺流纹 · 细密木理' },
  { id: 'rosewood', label: '深玫瑰木', detail: '蜿蜒流纹 · 红褐交织' },
  { id: 'hainan-huali', label: '海南黄花梨', detail: '卷曲鬼脸纹 · 暖金褐色' },
  { id: 'zitan', label: '小叶紫檀', detail: '细密横纹 · 深紫红色' },
  { id: 'suan-zhi', label: '大红酸枝', detail: '交错流纹 · 红褐木理' },
  { id: 'wenge', label: '鸡翅木', detail: '羽状条纹 · 深浅交织' },
  { id: 'black-walnut', label: '黑胡桃木', detail: '自然木纹' },
  { id: 'ebony', label: '黑檀·乌木', detail: '自然木理' },
  { id: 'huali', label: '花梨木', detail: '自然木纹' },
  { id: 'camphor', label: '香樟木', detail: '自然木理' },
].map((preset) => Object.freeze(preset)));

export const pieceSkins = Object.freeze([
  { id: 'ivory', label: '象牙', detail: '温润象牙色' },
  { id: 'maple', label: '浅枫木', detail: '轻浅细纹' },
  { id: 'beech', label: '浅榉木', detail: '细直木理' },
  { id: 'oak', label: '金橡木', detail: '暖金山纹' },
  { id: 'cherry', label: '樱桃木', detail: '柔顺暖木' },
  { id: 'walnut', label: '胡桃木', detail: '淡褐弧纹' },
  { id: 'rosewood', label: '玫瑰木', detail: '红褐流纹' },
  { id: 'horn-black', label: '黑牛角', detail: '黑褐层纹 · 密实丝理' },
  { id: 'horn-ivory', label: '白牛角', detail: '暖乳白色 · 层状缕纹' },
  { id: 'jade-white', label: '白玉', detail: '乳白云雾 · 细柔玉理' },
  { id: 'jade-celadon', label: '青玉', detail: '浅青云纹 · 温润玉色' },
  { id: 'jade-green', label: '碧玉', detail: '青绿云斑 · 润泽玉理' },
].map((preset) => Object.freeze(preset)));
